# Generated by Django 3.1.2 on 2020-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('recipient', models.TextField()),
                ('sum', models.IntegerField()),
                ('hash', models.TextField(unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=True)),
            ],
        ),
    ]
